ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

MONGODB_USERNAME: "thaileisme"
MONGODB_PASSWORD: "QyJkUimN33q38BZC"
MONGODB_HOST: "localhost"
MONGODB_PORT: '27017'
MONGODB_DB: "vietlinhtinh"

