access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: ${MONGODB_DB}
#      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.unecj4l.mongodb.net/
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}

logging:
  level:
    org.springframework.security: DEBUG
